# Generated by Django 4.2.5 on 2024-10-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deputado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomedeputado', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=14, null=True)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('rua', models.CharField(blank=True, max_length=250, null=True)),
                ('numero', models.CharField(blank=True, max_length=4, null=True)),
                ('complemento', models.CharField(blank=True, max_length=50, null=True)),
                ('bairro', models.CharField(blank=True, max_length=250, null=True)),
                ('cidade', models.CharField(blank=True, max_length=250, null=True)),
                ('uf', models.CharField(blank=True, default='RJ', max_length=2, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=15, null=True)),
                ('observacao', models.CharField(blank=True, max_length=250, null=True)),
                ('ativo', models.BooleanField(blank=True, default=True, max_length=1, null=True)),
                ('partido', models.CharField(max_length=100)),
                ('nomeurna', models.CharField(max_length=250)),
                ('numcandidatura', models.CharField(max_length=8)),
                ('numurna', models.CharField(max_length=8)),
                ('emailcaduf', models.EmailField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
