# Generated by Django 4.2.5 on 2024-10-29 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleitores', '0003_alter_eleitor_vereador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleitor',
            name='vereador',
        ),
    ]
