# Generated by Django 4.2.5 on 2024-10-29 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vereadores', '0003_alter_vereador_deputado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vereador',
            name='deputado',
        ),
    ]
